boot_up_3/AskDjango__beamin_st/beamin-st/baemin/urls.py
from django.urls import path

from . import views

app_name = 'baemin'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:shop_id>/new/', views.order_new, name='order_new'),
    #path('edit/<int:pk>/', views.post_edit, name='post_edit'),
    #path('delete/<int:pk>/', views.post_delete, name='post_delete'),
    #path('like', views.post_like, name='post_like'),
    #path('bookmark', views.post_bookmark, name='post_bookmark'),
    #path('comment/new/', views.comment_new, name="comment_new"),
    #path('comment/delete/', views.comment_delete, name="comment_delete"),
]

boot_up_3/AskDjango__beamin_st/beamin-st/baemin/models.py
from django.conf import settings
from django.db import models

class Shop(models.Model):
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)
    addr = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Item(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class Order(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item_set = models.ManyToManyField(Item)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)

    @property
    def total(self):
        return sum(item.price for item in self.item_set.all())

boot_up_3/AskDjango__beamin_st/beamin-st/baemin/forms.py
from django import forms

from .models import Order, Item

class OrderForm(forms.ModelForm):
    def __init__(self, shop, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_set'].queryset = Item.objects.filter(shop=shop.id)

    class Meta:
        model = Order
        fields = ('item_set',)

boot_up_3/AskDjango__beamin_st/beamin-st/baemin/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from .models import Shop
from .forms import OrderForm

def index(request):
    shop_list = Shop.objects.all()
    return render(request, 'baemin/index.html', {'shop_list': shop_list})

@login_required
def order_new(request, shop_id):
    shop = get_object_or_404(Shop, id=shop_id)
    if request.method == 'POST':
        form = OrderForm(shop, request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.shop = shop
            order.save()
            form.save_m2m()
            return redirect('accounts:profile')
    else:
        form = OrderForm(shop)
    return render(request, 'baemin/order_form.html', {'form': form, 'shop': shop})

boot_up_3/AskDjango__beamin_st/beamin-st/baemin/templates/baemin/index.html
{% extends "baemin/layout.html" %}

{% block content %}
<h3>안녕하세요. 배달의 민족입니다.</h3>
<br>
<h4>가게 목록</h4>
<table class="table">
  <thead>
    <tr>
      <th>가게명</th>
      <th>전화번호</th>
      <th>주소</th>
      <th>주문하기</th>
    </tr>
  </thead>
  <tbody>
    {% for shop in shop_list %}
    <tr>
      <td>{{ shop.name }}</td>
      <td>{{ shop.tel }}</td>
      <td>{{ shop.addr }}</td>
      <td><a href="{% url 'baemin:order_new' shop.id %}">주문하기</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

boot_up_3/AskDjango__beamin_st/beamin-st/baemin/templates/baemin/layout.html
{% extends "layout.html" %}

{% block link %}
{% if user.is_authenticated %}
<a href="{% url 'accounts:profile' %}">사용자 프로필</a> |
{% endif %}
{% endblock %}

boot_up_3/AskDjango__beamin_st/beamin-st/baemin/templates/baemin/order_form.html
{% extends "baemin/layout.html" %}

{% block content %}
<h3>{{ shop }} 주문하기</h3>
<br>
<h4>메뉴</h4>
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="주문하기">
</form>
{% endblock %}